services:
  api:
    container_name: api
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000

  db:
    container_name: db
    image: postgres:13.8
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: student-manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
